# Generated by Django 5.1.2 on 2025-12-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='tracker.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='share_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
